# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello',
  syntax='proto3',
  serialized_options=b'Z(github.com/avinassh/grpc-errors/go/hello',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\x12\x05hello\"\x18\n\x08HelloReq\x12\x0c\n\x04Name\x18\x01 \x01(\t\"\x17\n\x08HelloAge\x12\x0b\n\x03\x41ge\x18\x01 \x01(\x05\"\x1b\n\tHelloResp\x12\x0e\n\x06Result\x18\x01 \x01(\t2\xa7\x01\n\x0cHelloService\x12/\n\x08SayHello\x12\x0f.hello.HelloReq\x1a\x10.hello.HelloResp\"\x00\x12\x35\n\x0eSayHelloStrict\x12\x0f.hello.HelloReq\x1a\x10.hello.HelloResp\"\x00\x12/\n\x08\x41geHello\x12\x0f.hello.HelloAge\x1a\x10.hello.HelloResp\"\x00\x42*Z(github.com/avinassh/grpc-errors/go/hellob\x06proto3'
)




_HELLOREQ = _descriptor.Descriptor(
  name='HelloReq',
  full_name='hello.HelloReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='hello.HelloReq.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=46,
)


_HELLOAGE = _descriptor.Descriptor(
  name='HelloAge',
  full_name='hello.HelloAge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Age', full_name='hello.HelloAge.Age', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=71,
)


_HELLORESP = _descriptor.Descriptor(
  name='HelloResp',
  full_name='hello.HelloResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='hello.HelloResp.Result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['HelloReq'] = _HELLOREQ
DESCRIPTOR.message_types_by_name['HelloAge'] = _HELLOAGE
DESCRIPTOR.message_types_by_name['HelloResp'] = _HELLORESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloReq = _reflection.GeneratedProtocolMessageType('HelloReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQ,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloReq)
  })
_sym_db.RegisterMessage(HelloReq)

HelloAge = _reflection.GeneratedProtocolMessageType('HelloAge', (_message.Message,), {
  'DESCRIPTOR' : _HELLOAGE,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloAge)
  })
_sym_db.RegisterMessage(HelloAge)

HelloResp = _reflection.GeneratedProtocolMessageType('HelloResp', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESP,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloResp)
  })
_sym_db.RegisterMessage(HelloResp)


DESCRIPTOR._options = None

_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='hello.HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=103,
  serialized_end=270,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hello.HelloService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQ,
    output_type=_HELLORESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloStrict',
    full_name='hello.HelloService.SayHelloStrict',
    index=1,
    containing_service=None,
    input_type=_HELLOREQ,
    output_type=_HELLORESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AgeHello',
    full_name='hello.HelloService.AgeHello',
    index=2,
    containing_service=None,
    input_type=_HELLOAGE,
    output_type=_HELLORESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
